# Each route describes how an incoming URL is going to be processed by Platform.sh.
# "https://www.{default}/":
#     type: upstream
#     upstream: "app:http"

# "https://{default}/":
#     type: redirect
#     to: "https://www.{default}/"
"https://{all}/": { type: upstream, upstream: "app:http", cache: { enabled: false } }
"http://{all}/": { type: redirect, to: "https://{all}/" }
